{% set name = "floret" %}
{% set version = "0.10.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/explosion/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3460d35c83238319c75d5c53618fd92e31040e8a8e642c7b6e1f01af0bfa59fa
  patches:
    - 0001_do_not_hardcode_compiler.patch

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
  host:
    - python
    - numpy
    - pip
    - pybind11 >=2.2
    - setuptools >=0.7.0
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - floret
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/explosion/floret
  summary: fastText + Bloom embeddings for compact, full-coverage vectors with spaCy
  description: |
    floret is an extended version of fastText that can produce word 
    representations for any word from a compact vector table. It combines:
    - fastText's subwords to provide embeddings for any word
    - Bloom embeddings ("hashing trick") for a compact vector table
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/explosion/floret/

extra:
  recipe-maintainers:
    - jtilly
